<?php
// Set headers to force the browser to download the file as XML
header("Content-Type: text/xml");

// Dynamic data (You can change these values as per your requirement)

// mostly needed through database
$partyName = "Yash Chavan"; 
$reportName = "Yash";
$date = "20240401";
$voucherNumber = "1"; // append using code
$stock_item_1 = "Room Rent";
$room_rent_amount = "10000.00";
$total_sales_amount = "-25000.00";
$name = "BQ-1"; // through code
$voucher_receipt_id = "00000002";  // append using code
$voucher_receipt_Key = "00000010";  // append using code
$amount_receipt = "10000.00";

$companyName = "ABC Pvt Ltd";
$gstRegistrationType = "Regular";
$gstRegistration = "ABC Pvt Ltd";
$country = "India";
$sales_narration = "This is the Bill that Yash Chavan has to pay to Banquet Easy";
$special = "&#4;"; // The HTML entity
$decoded = html_entity_decode($special, ENT_QUOTES, 'UTF-8'); // Decode the entity
$ledger_name = "Banquet Sales";
$stock_item_2 = "Other Charges";
$amount_2 = "15000.00";
$bill_type = "New Ref";

//Dynamic data for receipt 
$guId_receipt = "00000002";
$billType_receipt = "Agst Ref";
$amount_minus_receipt = "-10000.00";
$cheque = 'Cheque';




// Escape special characters to be safe in XML context
$escapedDecoded = htmlspecialchars($decoded, ENT_QUOTES, 'UTF-8');

// Dynamic data (You can change these values as per your requirement)

$voucherType = "sales";
$billType = "New Ref";
$name = 'BQ-1';
$ledgerName = "Banquet Sales";
$voucher_ID = "00000001";
$voucher_Key = "00000008";
$guID = "00000001";
$reportName = "Yash";
$receipt_narration = "Yash Chavan payed 10,000 by cheque to banquet easy";


// Start of the XML structure
echo '<?xml version="1.0" encoding="UTF-8"?> 
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
  <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>' . $reportName . '</REPORTNAME>
        <STATICVARIABLES>
          <SVCURRENTCOMPANY>' . $companyName . '</SVCURRENTCOMPANY>
        </STATICVARIABLES>
      </REQUESTDESC>
      <REQUESTDATA>
        <!-- Start of the Sales voucher of 25,000 -->
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
          <VOUCHER REMOTEID="ef1532b1-c551-4b3f-ac45-04402e1668cc-'.$voucher_ID.'" VCHKEY="ef1532b1-c551-4b3f-ac45-04402e1668cc-0000b146:'.$voucher_Key.'" VCHTYPE="Sales" ACTION="Create" OBJVIEW="Invoice Voucher View">
            <OLDAUDITENTRYIDS.LIST TYPE="Number">
              <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
            </OLDAUDITENTRYIDS.LIST>
            <DATE>' . $date . '</DATE>
            <VCHSTATUSDATE>' . $date . '</VCHSTATUSDATE>
            <GUID>ef1532b1-c551-4b3f-ac45-04402e1668cc-'.$guID.'</GUID>
            <GSTREGISTRATIONTYPE>' . $gstRegistrationType . '</GSTREGISTRATIONTYPE>
            <VATDEALERTYPE>' . $gstRegistrationType . '</VATDEALERTYPE>
            <NARRATION>' . $sales_narration . '</NARRATION>
            <COUNTRYOFRESIDENCE>' . $country . '</COUNTRYOFRESIDENCE>
            <PARTYNAME>' . $partyName . '</PARTYNAME>
            <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="">' . $gstRegistration . '</GSTREGISTRATION>
            <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
            <PARTYLEDGERNAME>' . $partyName . '</PARTYLEDGERNAME>
            <VOUCHERNUMBER>' . $voucherNumber . '</VOUCHERNUMBER>
            <BASICBUYERNAME>' . $partyName . '</BASICBUYERNAME>
            <CMPGSTREGISTRATIONTYPE>' . $gstRegistrationType . '</CMPGSTREGISTRATIONTYPE>
            <PARTYMAILINGNAME>' . $partyName . '</PARTYMAILINGNAME>
            <CONSIGNEEMAILINGNAME>' . $partyName . '</CONSIGNEEMAILINGNAME>
            <CONSIGNEECOUNTRYNAME>' . $country . '</CONSIGNEECOUNTRYNAME>
            <BASICBASEPARTYNAME>' . $partyName . '</BASICBASEPARTYNAME>
            <NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>
            <CSTFORMISSUETYPE>Not Applicable</CSTFORMISSUETYPE>
            <CSTFORMRECVTYPE>Not Applicable</CSTFORMRECVTYPE>
            <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
            <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
            <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
            <VCHSTATUSVOUCHERTYPE>'.$voucherType.'</VCHSTATUSVOUCHERTYPE>
            <VCHSTATUSTAXUNIT>' . $companyName . '</VCHSTATUSTAXUNIT>
            <VCHGSTCLASS>Not Applicable</VCHGSTCLASS>
            <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
            <DIFFACTUALQTY>No</DIFFACTUALQTY>
            <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
            <ISDELETED>No</ISDELETED>
            <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
            <ASORIGINAL>No</ASORIGINAL>
            <AUDITED>No</AUDITED>
            <ISCOMMONPARTY>No</ISCOMMONPARTY>
            <FORJOBCOSTING>No</FORJOBCOSTING>
            <ISOPTIONAL>No</ISOPTIONAL>
            <EFFECTIVEDATE>' . $date . '</EFFECTIVEDATE>
            <USEFOREXCISE>No</USEFOREXCISE>
 <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
 <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
 <USEFORINTEREST>No</USEFORINTEREST>
 <USEFORGAINLOSS>No</USEFORGAINLOSS>
 <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
 <USEFORCOMPOUND>No</USEFORCOMPOUND>
 <USEFORSERVICETAX>No</USEFORSERVICETAX>
 <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
 <ISSYSTEM>No</ISSYSTEM>
 <ISFETCHEDONLY>No</ISFETCHEDONLY>
 <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
 <ISCANCELLED>No</ISCANCELLED>
 <ISONHOLD>No</ISONHOLD>
 <ISSUMMARY>No</ISSUMMARY>
 <ISECOMMERCESUPPLY>No</ISECOMMERCESUPPLY>
 <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
 <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
 <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
 <CMPGSTISOTHTERRITORYASSESSEE>No</CMPGSTISOTHTERRITORYASSESSEE>
 <PARTYGSTISOTHTERRITORYASSESSEE>No</PARTYGSTISOTHTERRITORYASSESSEE>
 <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
 <IRNCANCELLED>No</IRNCANCELLED>
 <IGNOREGSTCONFLICTINMIG>No</IGNOREGSTCONFLICTINMIG>
 <ISOPBALTRANSACTION>No</ISOPBALTRANSACTION>
 <IGNOREGSTFORMATVALIDATION>No</IGNOREGSTFORMATVALIDATION>
 <ISELIGIBLEFORITC>Yes</ISELIGIBLEFORITC>
 <UPDATESUMMARYVALUES>No</UPDATESUMMARYVALUES>
 <ISEWAYBILLAPPLICABLE>No</ISEWAYBILLAPPLICABLE>
 <ISDELETEDRETAINED>No</ISDELETEDRETAINED>
 <ISNULL>No</ISNULL>
 <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
 <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
 <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
 <ISEXER1NOPOVERWRITE>No</ISEXER1NOPOVERWRITE>
 <ISEXF2NOPOVERWRITE>No</ISEXF2NOPOVERWRITE>
 <ISEXER3NOPOVERWRITE>No</ISEXER3NOPOVERWRITE>
 <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
 <EXCISEOPENING>No</EXCISEOPENING>
 <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
 <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
 <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
 <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
 <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
 <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
 <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
 <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
 <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
 <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
 <VATADVANCEPAYMENT>No</VATADVANCEPAYMENT>
 <VATADVPAY>No</VATADVPAY>
 <ISCSTDELCAREDGOODSSALES>No</ISCSTDELCAREDGOODSSALES>
 <ISVATRESTAXINV>No</ISVATRESTAXINV>
 <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
 <ISISDVOUCHER>No</ISISDVOUCHER>
 <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
 <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
 <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
 <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
 <ISGSTREFUND>No</ISGSTREFUND>
 <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
 <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
 <VCHSTATUSISVCHNUMUSED>No</VCHSTATUSISVCHNUMUSED>
 <VCHGSTSTATUSISINCLUDED>No</VCHGSTSTATUSISINCLUDED>
 <VCHGSTSTATUSISUNCERTAIN>No</VCHGSTSTATUSISUNCERTAIN>
 <VCHGSTSTATUSISEXCLUDED>No</VCHGSTSTATUSISEXCLUDED>
 <VCHGSTSTATUSISAPPLICABLE>No</VCHGSTSTATUSISAPPLICABLE>
 <VCHGSTSTATUSISGSTR2BRECONCILED>No</VCHGSTSTATUSISGSTR2BRECONCILED>
 <VCHGSTSTATUSISGSTR2BONLYINPORTAL>No</VCHGSTSTATUSISGSTR2BONLYINPORTAL>
 <VCHGSTSTATUSISGSTR2BONLYINBOOKS>No</VCHGSTSTATUSISGSTR2BONLYINBOOKS>
 <VCHGSTSTATUSISGSTR2BMISMATCH>No</VCHGSTSTATUSISGSTR2BMISMATCH>
 <VCHGSTSTATUSISGSTR2BINDIFFPERIOD>No</VCHGSTSTATUSISGSTR2BINDIFFPERIOD>
 <VCHGSTSTATUSISRETEFFDATEOVERRDN>No</VCHGSTSTATUSISRETEFFDATEOVERRDN>
 <VCHGSTSTATUSISOVERRDN>No</VCHGSTSTATUSISOVERRDN>
 <VCHGSTSTATUSISSTATINDIFFDATE>No</VCHGSTSTATUSISSTATINDIFFDATE>
 <VCHGSTSTATUSISRETINDIFFDATE>No</VCHGSTSTATUSISRETINDIFFDATE>
 <VCHGSTSTATUSMAINSECTIONEXCLUDED>No</VCHGSTSTATUSMAINSECTIONEXCLUDED>
 <VCHGSTSTATUSISBRANCHTRANSFEROUT>No</VCHGSTSTATUSISBRANCHTRANSFEROUT>
 <VCHGSTSTATUSISSYSTEMSUMMARY>No</VCHGSTSTATUSISSYSTEMSUMMARY>
 <VCHSTATUSISUNREGISTEREDRCM>No</VCHSTATUSISUNREGISTEREDRCM>
 <VCHSTATUSISOPTIONAL>No</VCHSTATUSISOPTIONAL>
 <VCHSTATUSISCANCELLED>No</VCHSTATUSISCANCELLED>
 <VCHSTATUSISDELETED>No</VCHSTATUSISDELETED>
 <VCHSTATUSISOPENINGBALANCE>No</VCHSTATUSISOPENINGBALANCE>
 <VCHSTATUSISFETCHEDONLY>No</VCHSTATUSISFETCHEDONLY>
 <PAYMENTLINKHASMULTIREF>No</PAYMENTLINKHASMULTIREF>
 <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
 <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
 <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
 <HASCASHFLOW>No</HASCASHFLOW>
 <ISPOSTDATED>No</ISPOSTDATED>
 <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
 <ISINVOICE>Yes</ISINVOICE>
 <MFGJOURNAL>No</MFGJOURNAL>
 <HASDISCOUNTS>No</HASDISCOUNTS>
 <ASPAYSLIP>No</ASPAYSLIP>
 <ISCOSTCENTRE>No</ISCOSTCENTRE>
 <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
 <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
 <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
 <ISVOID>No</ISVOID>
 <ORDERLINESTATUS>No</ORDERLINESTATUS>
 <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
 <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
 <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
 <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
 <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
 <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
 <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
 <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
 <CHANGEVCHMODE>No</CHANGEVCHMODE>
 <RESETIRNQRCODE>No</RESETIRNQRCODE>
 <ALTERID> 1</ALTERID>
 <MASTERID> 1</MASTERID>
 <VOUCHERKEY>194914205827080</VOUCHERKEY>
 <VOUCHERRETAINKEY>1</VOUCHERRETAINKEY>
 <VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
 <EWAYBILLDETAILS.LIST> </EWAYBILLDETAILS.LIST>
 <EXCLUDEDTAXATIONS.LIST> </EXCLUDEDTAXATIONS.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <GSTADVADJDETAILS.LIST> </GSTADVADJDETAILS.LIST>
<!-- Inventory List Split Room Rent 10,000 -->
 <ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>'.$stock_item_1.'</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <ISAUTONEGATE>No</ISAUTONEGATE>
 <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
 <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
 <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
 <ISPRIMARYITEM>No</ISPRIMARYITEM>
 <ISSCRAP>No</ISSCRAP>
 <AMOUNT>'.$room_rent_amount.'</AMOUNT>
 <BATCHALLOCATIONS.LIST>
 <GODOWNNAME>Main Location</GODOWNNAME>
 <BATCHNAME>Primary Batch</BATCHNAME>
 <INDENTNO>' . $escapedDecoded . ' Not Applicable</INDENTNO>
 <ORDERNO>' . $escapedDecoded . ' Not Applicable</ORDERNO>
 <TRACKINGNUMBER>' . $escapedDecoded . ' Not Applicable</TRACKINGNUMBER>
 <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
 <AMOUNT>'.$room_rent_amount.'</AMOUNT>
 <ADDITIONALDETAILS.LIST> </ADDITIONALDETAILS.LIST>
 <VOUCHERCOMPONENTLIST.LIST> </VOUCHERCOMPONENTLIST.LIST>
 </BATCHALLOCATIONS.LIST>
 <ACCOUNTINGALLOCATIONS.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <LEDGERNAME>'.$ledger_name.'</LEDGERNAME>
 <GSTCLASS>' . $escapedDecoded . ' Not Applicable</GSTCLASS>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <LEDGERFROMITEM>No</LEDGERFROMITEM>
 <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
 <ISPARTYLEDGER>No</ISPARTYLEDGER>
 <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
 <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
 <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
 <AMOUNT>'.$room_rent_amount.'</AMOUNT>
 <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
 <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
 <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
 <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
 <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
 <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
 <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
 <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
 <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
 <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
 <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
 <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
 </ACCOUNTINGALLOCATIONS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <EXCISEALLOCATIONS.LIST> </EXCISEALLOCATIONS.LIST>
 <EXPENSEALLOCATIONS.LIST> </EXPENSEALLOCATIONS.LIST>
 </ALLINVENTORYENTRIES.LIST>
 <!-- Inventory List Split – Other Charges 15,000 -->
 <ALLINVENTORYENTRIES.LIST>
 <STOCKITEMNAME>'.$stock_item_2.'</STOCKITEMNAME>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <ISAUTONEGATE>No</ISAUTONEGATE>
 <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
 <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
 <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
 <ISPRIMARYITEM>No</ISPRIMARYITEM>
 <ISSCRAP>No</ISSCRAP>
 <AMOUNT>'.$amount_2.'</AMOUNT>
 <BATCHALLOCATIONS.LIST>
 <GODOWNNAME>Main Location</GODOWNNAME>
 <BATCHNAME>Primary Batch</BATCHNAME>
 <INDENTNO>' . $escapedDecoded . ' Not Applicable</INDENTNO>
 <ORDERNO>' . $escapedDecoded . ' Not Applicable</ORDERNO>
 <TRACKINGNUMBER>' . $escapedDecoded . ' Not Applicable</TRACKINGNUMBER>
 <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
 <AMOUNT>'.$amount_2.'</AMOUNT>
 <ADDITIONALDETAILS.LIST> </ADDITIONALDETAILS.LIST>
 <VOUCHERCOMPONENTLIST.LIST> </VOUCHERCOMPONENTLIST.LIST>
 </BATCHALLOCATIONS.LIST>
 <ACCOUNTINGALLOCATIONS.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <LEDGERNAME>'.$ledger_name.'</LEDGERNAME>
 <GSTCLASS>' . $escapedDecoded . ' Not Applicable</GSTCLASS>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <LEDGERFROMITEM>No</LEDGERFROMITEM>
 <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
 <ISPARTYLEDGER>No</ISPARTYLEDGER>
 <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
 <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
 <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
 <AMOUNT>'.$amount_2.'</AMOUNT>
 <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
 <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
 <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
 <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
 <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
 <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
 <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
 <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
 <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
 <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
 <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
 <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
 </ACCOUNTINGALLOCATIONS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <EXCISEALLOCATIONS.LIST> </EXCISEALLOCATIONS.LIST>
 <EXPENSEALLOCATIONS.LIST> </EXPENSEALLOCATIONS.LIST>
 </ALLINVENTORYENTRIES.LIST>
<!-- Writing the total price 25,000 -->
 <CONTRITRANS.LIST> </CONTRITRANS.LIST>
 <EWAYBILLERRORLIST.LIST> </EWAYBILLERRORLIST.LIST>
 <IRNERRORLIST.LIST> </IRNERRORLIST.LIST>
 <HARYANAVAT.LIST> </HARYANAVAT.LIST>
 <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
 <INVOICEDELNOTES.LIST> </INVOICEDELNOTES.LIST>
 <INVOICEORDERLIST.LIST> </INVOICEORDERLIST.LIST>
 <INVOICEINDENTLIST.LIST> </INVOICEINDENTLIST.LIST>
 <ATTENDANCEENTRIES.LIST> </ATTENDANCEENTRIES.LIST>
 <ORIGINVOICEDETAILS.LIST> </ORIGINVOICEDETAILS.LIST>
 <INVOICEEXPORTLIST.LIST> </INVOICEEXPORTLIST.LIST>
 <LEDGERENTRIES.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <LEDGERNAME>'.$partyName.'</LEDGERNAME>
 <GSTCLASS>' . $escapedDecoded . ' Not Applicable</GSTCLASS>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <LEDGERFROMITEM>No</LEDGERFROMITEM>
 <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
 <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
 <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
 <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
 <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
 <AMOUNT>'.$total_sales_amount.'</AMOUNT>
 <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
 <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
 <BILLALLOCATIONS.LIST>
 <NAME>'.$name.'</NAME>
 <BILLTYPE>'.$bill_type.'</BILLTYPE>
 <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
 <AMOUNT>'.$total_sales_amount.'</AMOUNT>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <STBILLCATEGORIES.LIST> </STBILLCATEGORIES.LIST>
 </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
 <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
 <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
 <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
 <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
 <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
 <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
 <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
 <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
 <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
 </LEDGERENTRIES.LIST>
 <GST.LIST> </GST.LIST>
 <STKJRNLADDLCOSTDETAILS.LIST> </STKJRNLADDLCOSTDETAILS.LIST>
 <PAYROLLMODEOFPAYMENT.LIST> </PAYROLLMODEOFPAYMENT.LIST>
 <ATTDRECORDS.LIST> </ATTDRECORDS.LIST>
 <GSTEWAYCONSIGNORADDRESS.LIST> </GSTEWAYCONSIGNORADDRESS.LIST>
 <GSTEWAYCONSIGNEEADDRESS.LIST> </GSTEWAYCONSIGNEEADDRESS.LIST>
 <TEMPGSTRATEDETAILS.LIST> </TEMPGSTRATEDETAILS.LIST>
 <TEMPGSTADVADJUSTED.LIST> </TEMPGSTADVADJUSTED.LIST>
 <GSTBUYERADDRESS.LIST> </GSTBUYERADDRESS.LIST>
 <GSTCONSIGNEEADDRESS.LIST> </GSTCONSIGNEEADDRESS.LIST>
 </VOUCHER>
 </TALLYMESSAGE>
 <!-- Start of the Receipt voucher of 10,000 -->
 <TALLYMESSAGE xmlns:UDF="TallyUDF">
 <VOUCHER REMOTEID="ef1532b1-c551-4b3f-ac45-04402e1668cc-'.$voucher_receipt_id.'"
VCHKEY="ef1532b1-c551-4b3f-ac45-04402e1668cc-0000b146:'.$voucher_receipt_Key.'" VCHTYPE="Receipt"
ACTION="Create" OBJVIEW="Accounting Voucher View">
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <DATE>'.$date.'</DATE>
 <VCHSTATUSDATE>'.$date.'</VCHSTATUSDATE>
 <GUID>ef1532b1-c551-4b3f-ac45-04402e1668cc-'.$guId_receipt.'</GUID>
 <NARRATION>' . $receipt_narration.' </NARRATION>
 <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="">ABC Pvt Ltd</GSTREGISTRATION>
 <VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME>
 <PARTYLEDGERNAME>'.$partyName.'</PARTYLEDGERNAME>
 <VOUCHERNUMBER>1</VOUCHERNUMBER>
 <CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>
 <NUMBERINGSTYLE>Auto Retain</NUMBERINGSTYLE>
 <CSTFORMISSUETYPE>' . $escapedDecoded . ' Not Applicable</CSTFORMISSUETYPE>
 <CSTFORMRECVTYPE>' . $escapedDecoded . ' Not Applicable</CSTFORMRECVTYPE>
 <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
 <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
 <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
 <VCHSTATUSVOUCHERTYPE>Receipt</VCHSTATUSVOUCHERTYPE>
 <VCHSTATUSTAXUNIT>'.$companyName.'</VCHSTATUSTAXUNIT>
 <VCHGSTCLASS>' . $escapedDecoded . ' Not Applicable</VCHGSTCLASS>
 <DIFFACTUALQTY>No</DIFFACTUALQTY>
 <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
 <ISDELETED>No</ISDELETED>
 <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
 <ASORIGINAL>No</ASORIGINAL>
 <AUDITED>No</AUDITED>
 <ISCOMMONPARTY>No</ISCOMMONPARTY>
 <FORJOBCOSTING>No</FORJOBCOSTING>
 <ISOPTIONAL>No</ISOPTIONAL>
 <EFFECTIVEDATE>'.$date.'</EFFECTIVEDATE>
 <USEFOREXCISE>No</USEFOREXCISE>
 <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
 <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
 <USEFORINTEREST>No</USEFORINTEREST>
 <USEFORGAINLOSS>No</USEFORGAINLOSS>
 <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
 <USEFORCOMPOUND>No</USEFORCOMPOUND>
 <USEFORSERVICETAX>No</USEFORSERVICETAX>
 <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
 <ISSYSTEM>No</ISSYSTEM>
 <ISFETCHEDONLY>No</ISFETCHEDONLY>
 <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
 <ISCANCELLED>No</ISCANCELLED>
 <ISONHOLD>No</ISONHOLD>
 <ISSUMMARY>No</ISSUMMARY>
 <ISECOMMERCESUPPLY>No</ISECOMMERCESUPPLY>
 <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
 <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
 <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
 <CMPGSTISOTHTERRITORYASSESSEE>No</CMPGSTISOTHTERRITORYASSESSEE>
 <PARTYGSTISOTHTERRITORYASSESSEE>No</PARTYGSTISOTHTERRITORYASSESSEE>
 <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
 <IRNCANCELLED>No</IRNCANCELLED>
 <IGNOREGSTCONFLICTINMIG>No</IGNOREGSTCONFLICTINMIG>
 <ISOPBALTRANSACTION>No</ISOPBALTRANSACTION>
 <IGNOREGSTFORMATVALIDATION>No</IGNOREGSTFORMATVALIDATION>
 <ISELIGIBLEFORITC>Yes</ISELIGIBLEFORITC>
 <UPDATESUMMARYVALUES>No</UPDATESUMMARYVALUES>
 <ISEWAYBILLAPPLICABLE>No</ISEWAYBILLAPPLICABLE>
 <ISDELETEDRETAINED>No</ISDELETEDRETAINED>
 <ISNULL>No</ISNULL>
 <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
 <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
 <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
 <ISEXER1NOPOVERWRITE>No</ISEXER1NOPOVERWRITE>
 <ISEXF2NOPOVERWRITE>No</ISEXF2NOPOVERWRITE>
 <ISEXER3NOPOVERWRITE>No</ISEXER3NOPOVERWRITE>
 <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
 <EXCISEOPENING>No</EXCISEOPENING>
 <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
 <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
 <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
 <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
 <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
 <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
 <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
 <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
 <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
 <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
 <VATADVANCEPAYMENT>No</VATADVANCEPAYMENT>
 <VATADVPAY>No</VATADVPAY>
 <ISCSTDELCAREDGOODSSALES>No</ISCSTDELCAREDGOODSSALES>
 <ISVATRESTAXINV>No</ISVATRESTAXINV>
 <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
 <ISISDVOUCHER>No</ISISDVOUCHER>
 <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
 <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
 <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
 <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
 <ISGSTREFUND>No</ISGSTREFUND>
 <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
 <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
 <VCHSTATUSISVCHNUMUSED>No</VCHSTATUSISVCHNUMUSED>
 <VCHGSTSTATUSISINCLUDED>No</VCHGSTSTATUSISINCLUDED>
 <VCHGSTSTATUSISUNCERTAIN>No</VCHGSTSTATUSISUNCERTAIN>
 <VCHGSTSTATUSISEXCLUDED>No</VCHGSTSTATUSISEXCLUDED>
 <VCHGSTSTATUSISAPPLICABLE>No</VCHGSTSTATUSISAPPLICABLE>
 <VCHGSTSTATUSISGSTR2BRECONCILED>No</VCHGSTSTATUSISGSTR2BRECONCILED>
 <VCHGSTSTATUSISGSTR2BONLYINPORTAL>No</VCHGSTSTATUSISGSTR2BONLYINPORTAL>
 <VCHGSTSTATUSISGSTR2BONLYINBOOKS>No</VCHGSTSTATUSISGSTR2BONLYINBOOKS>
 <VCHGSTSTATUSISGSTR2BMISMATCH>No</VCHGSTSTATUSISGSTR2BMISMATCH>
 <VCHGSTSTATUSISGSTR2BINDIFFPERIOD>No</VCHGSTSTATUSISGSTR2BINDIFFPERIOD>
 <VCHGSTSTATUSISRETEFFDATEOVERRDN>No</VCHGSTSTATUSISRETEFFDATEOVERRDN>
 <VCHGSTSTATUSISOVERRDN>No</VCHGSTSTATUSISOVERRDN>
 <VCHGSTSTATUSISSTATINDIFFDATE>No</VCHGSTSTATUSISSTATINDIFFDATE>
 <VCHGSTSTATUSISRETINDIFFDATE>No</VCHGSTSTATUSISRETINDIFFDATE>
 <VCHGSTSTATUSMAINSECTIONEXCLUDED>No</VCHGSTSTATUSMAINSECTIONEXCLUDED>
 <VCHGSTSTATUSISBRANCHTRANSFEROUT>No</VCHGSTSTATUSISBRANCHTRANSFEROUT>
 <VCHGSTSTATUSISSYSTEMSUMMARY>No</VCHGSTSTATUSISSYSTEMSUMMARY>
 <VCHSTATUSISUNREGISTEREDRCM>No</VCHSTATUSISUNREGISTEREDRCM>
 <VCHSTATUSISOPTIONAL>No</VCHSTATUSISOPTIONAL>
 <VCHSTATUSISCANCELLED>No</VCHSTATUSISCANCELLED>
 <VCHSTATUSISDELETED>No</VCHSTATUSISDELETED>
 <VCHSTATUSISOPENINGBALANCE>No</VCHSTATUSISOPENINGBALANCE>
 <VCHSTATUSISFETCHEDONLY>No</VCHSTATUSISFETCHEDONLY>
 <PAYMENTLINKHASMULTIREF>No</PAYMENTLINKHASMULTIREF>
 <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
 <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
 <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
 <HASCASHFLOW>Yes</HASCASHFLOW>
 <ISPOSTDATED>No</ISPOSTDATED>
 <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
 <ISINVOICE>No</ISINVOICE>
 <MFGJOURNAL>No</MFGJOURNAL>
 <HASDISCOUNTS>No</HASDISCOUNTS>
 <ASPAYSLIP>No</ASPAYSLIP>
 <ISCOSTCENTRE>No</ISCOSTCENTRE>
 <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
 <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
 <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
 <ISVOID>No</ISVOID>
 <ORDERLINESTATUS>No</ORDERLINESTATUS>
 <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
 <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
 <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
 <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
 <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
 <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
 <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
 <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
 <CHANGEVCHMODE>No</CHANGEVCHMODE>
 <RESETIRNQRCODE>No</RESETIRNQRCODE>
 <ALTERID> 2</ALTERID>
 <MASTERID> 2</MASTERID>
 <VOUCHERKEY>194914205827088</VOUCHERKEY>
 <VOUCHERRETAINKEY>1</VOUCHERRETAINKEY>
 <VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
 <EWAYBILLDETAILS.LIST> </EWAYBILLDETAILS.LIST>
 <EXCLUDEDTAXATIONS.LIST> </EXCLUDEDTAXATIONS.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <GSTADVADJDETAILS.LIST> </GSTADVADJDETAILS.LIST>
 <CONTRITRANS.LIST> </CONTRITRANS.LIST>
 <EWAYBILLERRORLIST.LIST> </EWAYBILLERRORLIST.LIST>
 <IRNERRORLIST.LIST> </IRNERRORLIST.LIST>
 <HARYANAVAT.LIST> </HARYANAVAT.LIST>
 <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
 <INVOICEDELNOTES.LIST> </INVOICEDELNOTES.LIST>
 <INVOICEORDERLIST.LIST> </INVOICEORDERLIST.LIST>
 <INVOICEINDENTLIST.LIST> </INVOICEINDENTLIST.LIST>
 <ATTENDANCEENTRIES.LIST> </ATTENDANCEENTRIES.LIST>
 <ORIGINVOICEDETAILS.LIST> </ORIGINVOICEDETAILS.LIST>
 <INVOICEEXPORTLIST.LIST> </INVOICEEXPORTLIST.LIST>
 <ALLLEDGERENTRIES.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <APPROPRIATEFOR>' . $escapedDecoded . ' Not Applicable</APPROPRIATEFOR>
 <LEDGERNAME>Yash Chavan</LEDGERNAME>
 <GSTCLASS>' . $escapedDecoded . ' Not Applicable</GSTCLASS>
 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
 <LEDGERFROMITEM>No</LEDGERFROMITEM>
 <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
 <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
 <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
 <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
 <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
 <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
 <AMOUNT>'.$amount_receipt.'</AMOUNT>
 <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
 <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
 <BILLALLOCATIONS.LIST>
 <NAME>'.$name.'</NAME>
 <BILLTYPE>'.$billType_receipt.'</BILLTYPE>
 <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
 <AMOUNT>'.$amount_receipt.'</AMOUNT>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <STBILLCATEGORIES.LIST> </STBILLCATEGORIES.LIST>
 </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
 <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
 <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
 <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
 <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
 <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
 <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
 <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
 <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
 <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
 </ALLLEDGERENTRIES.LIST>
 <ALLLEDGERENTRIES.LIST>
 <OLDAUDITENTRYIDS.LIST TYPE="Number">
 <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
 </OLDAUDITENTRYIDS.LIST>
 <LEDGERNAME>'. $cheque .'</LEDGERNAME>
 <GSTCLASS>' . $escapedDecoded . ' Not Applicable</GSTCLASS>
 <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
 <LEDGERFROMITEM>No</LEDGERFROMITEM>
 <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
 <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
 <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
 <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
 <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
 <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
 <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
 <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
 <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
 <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
 <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
 <AMOUNT>'.$amount_minus_receipt.'</AMOUNT>
 <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
 <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>
 <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
 <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
 <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
 <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
 <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
 <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
 <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
 <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
 <RATEDETAILS.LIST> </RATEDETAILS.LIST>
 <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
 <CENVATDUTYALLOCATIONS.LIST> </CENVATDUTYALLOCATIONS.LIST>
 <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
 <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
 <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
 <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
 <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
 <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
 <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
 <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
 <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
 <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
 <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
 <TAXTYPEALLOCATIONS.LIST> </TAXTYPEALLOCATIONS.LIST>
 </ALLLEDGERENTRIES.LIST>
 <GST.LIST> </GST.LIST>
 <STKJRNLADDLCOSTDETAILS.LIST> </STKJRNLADDLCOSTDETAILS.LIST>
 <PAYROLLMODEOFPAYMENT.LIST> </PAYROLLMODEOFPAYMENT.LIST>
 <ATTDRECORDS.LIST> </ATTDRECORDS.LIST>
 <GSTEWAYCONSIGNORADDRESS.LIST> </GSTEWAYCONSIGNORADDRESS.LIST>
 <GSTEWAYCONSIGNEEADDRESS.LIST> </GSTEWAYCONSIGNEEADDRESS.LIST>
 <TEMPGSTRATEDETAILS.LIST> </TEMPGSTRATEDETAILS.LIST>
 <TEMPGSTADVADJUSTED.LIST> </TEMPGSTADVADJUSTED.LIST>
 <GSTBUYERADDRESS.LIST> </GSTBUYERADDRESS.LIST>
 <GSTCONSIGNEEADDRESS.LIST> </GSTCONSIGNEEADDRESS.LIST>
 </VOUCHER>
 </TALLYMESSAGE>
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>';
?>
